Słownik produktów, strona płatności
AdiiDev/Numerology pull request #66
Opened 2023-06-04 18:35 UTC by roller0201

2023-06-05 06:13 UTC, AdiiDev commented on Numerology/Numerology/clientapp/src/components/common/RHFAutocompleteClient.jsx
> +          renderInput={(params) => <TextField required={true} {...params} label={t(label)} margin='normal' variant='outlined' />}
```suggestion
          renderInput={(params) => <TextField required={required} {...params} label={t(label)} margin='normal' variant='outlined' />}
```

2023-06-05 06:13 UTC, AdiiDev commented on Numerology/Numerology/clientapp/src/components/common/SwitchReusable.jsx
> +const SwitchReusable = ({ name, label, control, defaultValue }) => {
DefaultValue nie powinno być potrzebne

2023-06-05 06:13 UTC, AdiiDev commented on Numerology/Numerology/clientapp/src/components/dictionaries/ProductsFormDialog.jsx
> +          <TextField variant='standard' {...register('name')} label={t('Designation')} autoFocus onKeyPress={handleKeyPress} required />
```suggestion
          <TextField variant='standard' {...register('name')} label={t('Designation')} autoFocus required />
```
To można zrobić lepiej

2023-06-05 06:13 UTC, AdiiDev commented on Numerology/Numerology/clientapp/src/components/dictionaries/ProductsTable.jsx
> +      setCount(filteredProducts.length)
Po co ten count?

2023-06-05 06:13 UTC, AdiiDev commented on Numerology/Numerology/clientapp/src/services/ConfigSlice.js
> +    reminderInterval: null,
Raczej domyślna wartość powinna być podana

2023-06-05 07:21 UTC, roller0201 commented on Numerology/Numerology/clientapp/src/services/ConfigSlice.js
> +    reminderInterval: null,
Ustawiam domyślną wartość w samym komponencie ustawień, w taki sam sposób jak robię to w przypadku bussinesHours. Więc albo zmieniamy to wszędzie, albo zostawiamy tak jak jest.

2023-06-05 07:27 UTC, AdiiDev commented on Numerology/Numerology/clientapp/src/services/ConfigSlice.js
> +    reminderInterval: null,
Do przegadania, reminderInterval nie powinno mieć initState jako null

2023-06-05 07:27 UTC, roller0201 commented on Numerology/Numerology/clientapp/src/services/ConfigSlice.js
> +    reminderInterval: null,
Dodałem też defaultValue dla tego po stronie BE.

2023-06-05 07:35 UTC, roller0201 commented on Numerology/Numerology/clientapp/src/components/common/RHFAutocompleteClient.jsx
> +          renderInput={(params) => <TextField required={true} {...params} label={t(label)} margin='normal' variant='outlined' />}
Poprawione, rzeczywiście głupotę zrobiłem.

2023-06-05 07:36 UTC, roller0201 commented on Numerology/Numerology/clientapp/src/components/common/SwitchReusable.jsx
> +const SwitchReusable = ({ name, label, control, defaultValue }) => {
To muszę Ci pokazać, bez defaultValue konsola wali warningiem o zmianie niekontrolowanego komponentu na kontrolowany etc.

2023-06-05 07:37 UTC, roller0201 commented on Numerology/Numerology/clientapp/src/components/dictionaries/ProductsFormDialog.jsx
> +          <TextField variant='standard' {...register('name')} label={t('Designation')} autoFocus onKeyPress={handleKeyPress} required />
To musisz mi wyjaśnić co masz na myśli.

2023-06-05 07:37 UTC, roller0201 commented on Numerology/Numerology/clientapp/src/components/dictionaries/ProductsTable.jsx
> +      setCount(filteredProducts.length)
Zmieniłem we wszystkich słownikach, w ktorych nie otrzymuje z BE counta i usunąłem ten state. Będziesz widział w najnowszym commicie.

2023-06-06 15:56 UTC, AdiiDev requested changes

2023-06-06 15:56 UTC, AdiiDev commented on Numerology/Numerology/clientapp/src/components/calendar/CalendarMeetingsForm.jsx
> +        id: editMeetingData !== null ? editMeetingData.id : data.id,
Nope paymentId != meetingId. Ale zabrakło w payment powiązania z meeting po stronie BE.

2023-06-06 15:56 UTC, AdiiDev commented on Numerology/Numerology/clientapp/src/components/payments/PaymentsFilterDrawer.jsx
> +  const initialState = {
Ta definicja inistialState to zbędna w samym komponencie

2023-06-06 15:56 UTC, AdiiDev commented on Numerology/Numerology/clientapp/src/components/payments/PaymentsFilterDrawer.jsx
> +      ...(filter?.startDate || filter?.endDate || filter?.client || filter?.category || filter?.isPaid !== false || filter?.ePay !== false ? filter : initialState),
A to jest jakiś potworek

2023-06-06 15:56 UTC, AdiiDev commented on Numerology/Numerology/clientapp/src/pages/PaymentsPage.jsx
> +        originalPaymentsRef.current = response.result
Dlaczego ref a nie state?

2023-06-07 10:40 UTC, AdiiDev approved these changes

2023-06-07 10:40 UTC, merged